import type { NextPage } from 'next'
import Head from 'next/head'

import Hero from '../components/hero/Hero'
import Footer from '../components/footer/Footer'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <Footer />
    </div>
  )
}

export default Home
